// ============================================================
// PRODUCTION CONFIG - Auto-generated by GitHub Actions
// ============================================================
// ⚠️ This file is generated during deployment and should NOT
// be committed to GitHub!
// ============================================================

const CONFIG = {
    // These values come from GitHub Secrets
    SUPABASE_URL: 'YOUR_SUPABASE_URL_WILL_BE_HERE',
    SUPABASE_ANON_KEY: 'YOUR_SUPABASE_ANON_KEY_WILL_BE_HERE',
    
    // App Configuration
    APP_NAME: 'NTWC_MPU_DRWS',
    APP_VERSION: '2.0',
    APP_ENV: 'production',
    ENABLE_DEBUG: false
};

// Make it available globally
if (typeof window !== 'undefined') {
    window.__CONFIG__ = CONFIG;
}

// Export for Node.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = CONFIG;
}

console.log('✅ Production config loaded successfully');
console.log('📊 Environment:', CONFIG.APP_ENV);
